kind: pipeline
type: docker
name: default

workspace:
  path: /myproject/source

steps:
  - name: zipping the source file
    image: alpine:latest
    commands:
      - apk update
      - apk add zip
      - cd /myproject/source
      - zip -r sourcecode-${DRONE_COMMIT_SHA:0:8}.zip . 
    volumes:
      - name: sourcefile
        path: /myproject/source/
    
  
  - name: source s3 bundle
    image: plugins/s3
    volumes:
      - name: sourcefile
        path: /myproject/source/
    settings:
      bucket: drone-node-test
      region: ap-southeast-2
      access_key:
        from_secret: aws_access_key
      secret_key:
        from_secret: aws_secret_key
      source: /myproject/source/sourcecode-${DRONE_COMMIT_SHA:0:8}.zip
      target: /
  
  
  - name: deploy to elastic beanstalk  
    image: pelotech/drone-elastic-beanstalk
    settings: 
      access_key:
        from_secret: aws_access_key 
      secret_key:
        from_secret: aws_secret_key
      region: ap-southeast-2
      application: drone ci test
      version_label: version-${DRONE_COMMIT_SHA:0:8}
      description: Deployed with DroneCI
      bucket: drone-node-test
      bucket_key: myproject/source/sourcecode-${DRONE_COMMIT_SHA:0:8}.zip
      environment_name: DroneCiTest-env-1
      environment_update: true