kind: pipeline
type: docker
name: default

pipeline:
  install_dependencies:
    image: node
    commands:
      - npm install

  beanstalk:
    image: pelotech/drone-elastic-beanstalk
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_ID} 
    region: ap-southeast-2
    application: 
    version_label: v1
    description: Deployed with DroneCI
    auto_create: true
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_ID ]

      