kind: pipeline
type: docker
name: default

pipeline:
  beanstalk:
    image: pelotech/drone-elastic-beanstalk
    access_key: AKIAUIJGMTYLC7BDR7WR
    secret_key: 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
    region: ap-southeast-2
    application: drone-ci-tester
    version_label: v1
    description: Deployed with DroneCI
    auto_create: true

      